  
  version: '3'
    
  services:
    db:
        image: postgres
        container_name: db
        environment:
          - POSTGRES_DB=django
          - POSTGRES_USER=django
          - POSTGRES_PASSWORD=startup
        ports: 
          - "5432:5432"
    redis:
        image: redis
        container_name: redis
        ports:
          - "6379:6379"
    web:
      build: ./docker/web
      container_name: web
      volumes:
        - ./docker/web://web
      ports:
        - "8000:8000"
      depends_on:
        - db