  
  version: '3'
    
  services:
    postgres:
        build: ./docker/postgres
        container_name: postgres
        volumes:
          - pgdata:/var/lib/postgresql/data
        environment:
          - POSTGRES_DB=django
          - POSTGRES_USER=django
          - POSTGRES_PASSWORD=startup
        ports: 
          - "5432:5432"
    redis:
        build: ./docker/redis
        container_name: redis
        volumes:
          - ./docker/redis:/data
        ports:
          - "6379:6379"
    web:
      build: ./docker/web
      container_name: web
      volumes:
        - ./docker/web://web
      ports:
        - "8000:8000"
        - "8088:8088"

      depends_on:
        - postgres
        - redis
  volumes:
    pgdata:
        external: false