  
  version: '3'
    
  services:
    postgres:
        build: ./docker/postgres
        container_name: postgres
        restart: unless-stopped
        volumes:
          - pgdata:/var/lib/postgresql/data
          - ./docker/postgres/docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
        environment:
          - POSTGRES_DB=django
          - POSTGRES_USER=django
          - POSTGRES_PASSWORD=startup
        ports: 
          - "5432:5432"
    redis:
        build: ./docker/redis
        container_name: redis
        restart: unless-stopped
        volumes:
          - redisdata:/data
        ports:
          - "6379:6379"
    minio:
      build: ./docker/minio
      container_name: minio
      volumes:
        - ./docker/minio:/data
      ports:
        - "9000:9000"
        - "9001:9001"
    dagster:
      build: ./docker/dagster
      container_name: dagster
      volumes:
        - ./docker/dagster:/data
      ports:
        - "3000:3000"
      environment: 
        - DAGSTER_PG_USERNAME=dagster
        - DAGSTER_PG_PASSWORD=dagster
        - DAGSTER_PG_HOST=postgres
        - DAGSTER_PG_DB=dagster
      depends_on:
      - postgres
    web:
      build: ./docker/web
      container_name: web
      volumes:
        - ./docker/web://web
      ports:
        - "8000:8000"
        - "8088:8088"
      depends_on:
        - postgres
        - redis
    spark:
      build: ./docker/spark
      container_name: spark
      ports: 
        - "8888:8888"
      environment:
        - JUPYTER_ENABLE_LAB=yes
  volumes:
    pgdata:
        external: false
    redisdata:
        external: false