# Generated by Django 3.2.7 on 2021-09-12 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='delimiter',
            field=models.CharField(choices=[(',', 'comma'), ('/t', 'tab')], default=',', max_length=2),
        ),
        migrations.AddField(
            model_name='dataset',
            name='header',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='connection_type',
            field=models.CharField(choices=[('local text', 'local text'), ('Snowflake', 'Snowflake')], default='csv', max_length=20),
        ),
    ]
